New schema to replace ep00
ess-dmsc/streaming-data-types pull request #70
Opened 2022-02-16 13:19 UTC by SkyToGround

### Description of Work

Other than the documentation changes, this PR is intended as a replacement for `ep00`. For this particular purpose it removes the use of unsigned integers and adds a few possible EPICS (pvAccess) connection states/events.

### Issue

*ECDC-2749

### Developer Checklist

- [ ] If there are new schema in this PR I have added them to the list in README.md
- [ ] If there are breaking changes to a schema, I have used a new file identifier and updated the list in README.md
- [ ] There is some documentation here or in the flat buffer file on the use case for this data, including which component is intended to send the data and/or which is the intended receiver.

## Approval Criteria

This PR should not be merged until Tobias R, Mark K and Jack H have given their explicit approval in the comments section.

2022-03-25 15:25 UTC, zjttoefs requested changes

2022-03-25 15:25 UTC, zjttoefs commented on README.md
> +* Tables should use _UpperCamelCase_.
Why the italics here but not for snake_case?

2022-03-25 15:25 UTC, zjttoefs commented on README.md
> +| rf5k | `rf5k_forwarder_config.fbs     ` | Configuration update for Forwarder
I guess this table renders prettier? Nice. But it would need to be updated with what has been merged in the meantime.

2022-03-25 15:25 UTC, zjttoefs commented on schemas/pvCn_epics_pv_connection.fbs
> +// Represent events about the underlying EPICS connection.
I would have merged that file on its own. 👍

2022-03-28 20:08 UTC, SkyToGround commented on README.md
> +* Fields should use snake_case.
```suggestion
* Fields should use *snake_case*.
```

2022-03-28 20:13 UTC, SkyToGround commented on README.md
> +The file identifiers (also called "schema id") must be unique on the network. When creating a new schema, try to pick a schema id for your new schema that is memorable or failing that, generate a ran
Seeing as we are using these identifiers in our day to day work. I think random numbers (characters) are terrible for communication and productivity. Naming things is hard but we do not make things easier for our selves by picking random function names.

2022-03-28 20:19 UTC, SkyToGround commented on README.md
> +| hs00 | `hs00_event_histogram.fbs      ` | Event histogram stored in n dim array
```suggestion
| hs00 | `hs00_event_histogram.fbs      ` | Event histogram stored in n dim array
| hs01 | `hs01_event_histogram.fbs      ` | Event histogram stored in n dim array
```

2022-03-30 06:24 UTC, mkoennecke commented
I am OK with this.

2022-09-13 07:05 UTC, merged